#
# GPT-1 Unsupervised Pre-training
#
# Paper: "Improving Language Understanding by Generative Pre-Training"
#        Radford et al., OpenAI, 2018
#
# Usage:
#   python gpt1_pretrain.py [n_epochs]
#
#   Copyright (c) 2026, Hironobu Suzuki @ interdb.jp

import os
import sys
import time
import logging
import numpy as np

if len(sys.argv) <= 1:
    print("Syntax Error:\n\tpython gpt1_pretrain.py [n_epochs]")
    sys.exit(1)

# Enable Metal GPU (M1/M2 Mac)
os.environ.setdefault("TF_METAL_DEVICE_ENABLE", "1")

import tensorflow as tf

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from gpt1_model import (
    GPT1Model,
    GPT1_CONFIG,
    GPT1LRSchedule,
    build_optimizer,
    build_checkpoint_manager,
    make_checkpoint_path,
    get_device,
)

from prepare_datasets import (
    SNLI_CONFIG,
    check_required_files,
)


logging.getLogger("tensorflow").setLevel(logging.ERROR)

DEVICE = get_device()

if check_required_files() == False:
    print("Execute prepare_datasets.py.")
    sys.exit(1)

# ============================================================
# Configuration
# ============================================================

CHECKPOINT = True

PRETRAIN_CONFIG = {
    "n_epochs": 100,
    "batch_size": 128,
    "seq_len": GPT1_CONFIG["max_seq_len"],  # context window length
    "warmup_steps": 500,
    "max_lr": 2.5e-4,
    "grad_clip": 1.0,
    "log_every": 10,  # print every N batches
    "checkpoint_dir": "./checkpoints",
}


# ============================================================
# Loss function - masked language-model cross-entropy
# ============================================================

_lm_loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True, reduction="none"
)


def lm_loss_fn(targets, logits):
    """
    Language-model cross-entropy, ignoring padding positions (token-id == 0).

    targets : (B, T)     integer next-token ids;  0 = pad -> excluded
    logits  : (B, T, V)  raw predicted logits
    Returns : scalar mean loss
    """
    loss = _lm_loss_object(targets, logits)  # (B, T)
    mask = tf.cast(tf.not_equal(targets, 0), tf.float32)
    loss = loss * mask
    return tf.reduce_sum(loss) / (tf.reduce_sum(mask) + 1e-9)


# ============================================================
# Dataset builder
# ============================================================


def load_pretrain_text(txt_path: str) -> list[str]:
    """
    Load a text file containing one sentence per line (generated by prepare_datasets.py).

    Parameters
    ----------
    txt_path : str  Path to ./data/pretrain/snli_pretrain.txt

    Returns
    -------
    list[str]  A list of strings, where each element is a line from the file.
    """
    if not os.path.exists(txt_path):
        raise FileNotFoundError(
            f"\n[Error] Pretraining text file not found: {txt_path}\n"
            f"  Run prepare_datasets.py first:\n"
            f"  $ python prepare_datasets.py\n"
        )
    with open(txt_path, encoding="utf-8") as fh:
        lines = [ln.rstrip("\n") for ln in fh if ln.strip()]
    print(f"[Corpus] {txt_path} -> {len(lines):,} sentences")
    return lines


def build_pretrain_dataset(
    token_ids_list: list[list[int]],
    seq_len: int,
    batch_size: int,
    shuffle: bool = True,
    shuffle_buffer: int = 10_000,
    seed: int = 42,
) -> tf.data.Dataset:
    """
    Build a tf.data.Dataset by splitting all token sequences into chunks of width seq_len.

    Call this function with seq_len = max\\_seq\\_len + 1 so that input_ids will have a shape of (B, seq_len + 1).
    Shift the tokens using [:, :-1] and [:, 1:] within the training step.

    Returns
    -------
    tf.data.Dataset  shape=(batch_size, seq_len)  dtype=int32
    """
    all_tokens: list[int] = []
    for ids in token_ids_list:
        all_tokens.extend(ids)

    n_chunks = len(all_tokens) // seq_len
    total_used = n_chunks * seq_len
    chunks = np.array(all_tokens[:total_used], dtype=np.int32).reshape(
        n_chunks, seq_len
    )

    print(
        f"[PretrainDataset]  sentences={len(token_ids_list):,}  "
        f"total_tokens={len(all_tokens):,}  "
        f"chunks={n_chunks:,}  seq_len={seq_len}"
    )

    ds = tf.data.Dataset.from_tensor_slices(chunks)
    if shuffle:
        ds = ds.shuffle(min(shuffle_buffer, n_chunks), seed=seed)
    ds = ds.batch(batch_size, drop_remainder=True).prefetch(tf.data.AUTOTUNE)
    return ds


# ============================================================
# Metrics
# ============================================================

train_loss = tf.keras.metrics.Mean(name="train_loss")
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name="train_accuracy")

# ============================================================
# @tf.function training step
# ============================================================

_pretrain_step_signature = [
    tf.TensorSpec(shape=(None, None), dtype=tf.int32),
]


def make_pretrain_step(model: GPT1Model, optimizer, grad_clip: float = 1.0):

    @tf.function(input_signature=_pretrain_step_signature)
    def pretrain_step(input_ids):
        x_input = input_ids[:, :-1]  # (B, T-1)
        x_target = input_ids[:, 1:]  # (B, T-1)

        with tf.device(DEVICE):
            with tf.GradientTape() as tape:
                hidden_states, _ = model(x_input, training=True)
                lm_logits = model.compute_lm_logits(hidden_states)
                loss = lm_loss_fn(x_target, lm_logits)

            gradients = tape.gradient(loss, model.trainable_variables)
            gradients, _ = tf.clip_by_global_norm(gradients, grad_clip)
            optimizer.apply_gradients(zip(gradients, model.trainable_variables))

        train_loss(loss)
        train_accuracy(x_target, lm_logits)

    return pretrain_step


# ============================================================
# Training loop
# ============================================================


def pretrain(
    model: GPT1Model,
    optimizer,
    dataset: tf.data.Dataset,
    n_epochs: int,
    ckpt_manager=None,
    log_every: int = 10,
    grad_clip: float = 1.0,
    start_epoch: int = 1,
) -> None:
    step_fn = make_pretrain_step(model, optimizer, grad_clip)

    for epoch in range(start_epoch, n_epochs + 1):
        start = time.time()

        train_loss.reset_state()
        train_accuracy.reset_state()

        for batch, input_ids in enumerate(dataset):
            with tf.device(DEVICE):
                input_ids = tf.identity(input_ids)
            step_fn(input_ids)

            if batch % log_every == 0:
                perplexity = tf.exp(train_loss.result())
                current_lr = float(optimizer.learning_rate(optimizer.iterations))
                print(
                    f"Epoch {epoch} Batch {batch:>5d}  "
                    f"Loss {train_loss.result():.4f}  "
                    f"Ppl {float(perplexity):.2f}  "
                    f"Accuracy {train_accuracy.result():.4f}  "
                    f"LR {current_lr:.2e}"
                )

        if CHECKPOINT and ckpt_manager is not None:
            ckpt_save_path = ckpt_manager.save()
            print(f"Saving checkpoint for epoch {epoch} at {ckpt_save_path}")

        elapsed = time.time() - start
        perplexity = tf.exp(train_loss.result())
        print(
            f"Epoch {epoch}/{n_epochs}  "
            f"Loss {train_loss.result():.4f}  "
            f"Ppl {float(perplexity):.2f}  "
            f"Accuracy {train_accuracy.result():.4f}  "
            f"Time {elapsed:.1f}s\n"
        )

    print("Pre-training complete.")


if __name__ == "__main__":

    _tp = os.path.join(os.path.dirname(os.path.abspath(__file__)), "text_processing")
    sys.path.insert(0, _tp)
    from bpe_encoder import BPEEncoder, BPETrainer  # noqa: E402
    from text_normalizer import fix_text  # noqa: E402
    import re

    _n_epochs = int(sys.argv[1]) if len(sys.argv) > 1 else 1

    _pretrain_txt = SNLI_CONFIG["pretrain_txt"]
    _vocab_path = SNLI_CONFIG["vocab_file"]
    _merges_path = SNLI_CONFIG["merges_file"]

    # BPE encoder
    print(f"[BPE] Loading  vocab={_vocab_path}  merges={_merges_path}")
    enc = BPEEncoder.from_files(_vocab_path, _merges_path)
    print(f"[BPE] Vocab size: {enc.vocab_size:,}")

    # Read Text and Tokenized
    sentences = load_pretrain_text(_pretrain_txt)
    print(f"[Tokenize] {len(sentences):,} sentences ...")
    token_ids = [enc.encode(fix_text(s)) for s in sentences]

    # Dataset
    _SEQ_LEN = PRETRAIN_CONFIG["seq_len"] + 1  # target:last token
    dataset = build_pretrain_dataset(
        token_ids,
        seq_len=_SEQ_LEN,
        batch_size=PRETRAIN_CONFIG["batch_size"],
    )

    _n_batches = sum(1 for _ in dataset)
    _total_steps = _n_batches * _n_epochs
    print(f"[Dataset] Batches/epoch={_n_batches:,}  Total steps={_total_steps:,}")

    # Model
    with tf.device(DEVICE):
        model = GPT1Model(
            num_layers=GPT1_CONFIG["num_layers"],
            d_model=GPT1_CONFIG["d_model"],
            num_heads=GPT1_CONFIG["num_heads"],
            d_ffn=GPT1_CONFIG["d_ffn"],
            vocab_size=enc.vocab_size,
            max_seq_len=GPT1_CONFIG["max_seq_len"],
            dropout_rate=GPT1_CONFIG["dropout_rate"],
            name="gpt1",
        )

    # Optimizer
    lr_schedule = GPT1LRSchedule(
        max_lr=PRETRAIN_CONFIG["max_lr"],
        warmup_steps=PRETRAIN_CONFIG["warmup_steps"],
        total_steps=max(_total_steps, PRETRAIN_CONFIG["warmup_steps"] + 1),
    )
    optimizer = build_optimizer(lr_schedule, weight_decay=GPT1_CONFIG["l2_weight"])

    # Checkpoint
    ckpt_path = make_checkpoint_path(
        PRETRAIN_CONFIG["checkpoint_dir"],
        "pretrain",
        GPT1_CONFIG["num_layers"],
        GPT1_CONFIG["d_model"],
        GPT1_CONFIG["d_ffn"],
        GPT1_CONFIG["num_heads"],
    )
    ckpt, ckpt_manager = build_checkpoint_manager(model, optimizer, ckpt_path)

    start_epoch = 1
    if ckpt_manager.latest_checkpoint:
        ckpt.restore(ckpt_manager.latest_checkpoint).expect_partial()
        print(f"[Checkpoint] Restored: {ckpt_manager.latest_checkpoint}")

        start_epoch += int(
            re.search(r"-(\d+)$", ckpt_manager.latest_checkpoint).group(1)
        )

    # Run
    pretrain(
        model=model,
        optimizer=optimizer,
        dataset=dataset,
        n_epochs=_n_epochs,
        ckpt_manager=ckpt_manager,
        log_every=PRETRAIN_CONFIG["log_every"],
        grad_clip=PRETRAIN_CONFIG["grad_clip"],
        start_epoch=start_epoch,
    )
